import type { Metadata } from "next";
import Header from "./Components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-neutral-700">
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
