import { BookmarkProvider } from "@/contexts/BookmarkContext";
import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BookmarkProvider>
      <html lang="en">
        <body className="bg-neutral-700">
          <Navbar></Navbar>
          {children}
        </body>
      </html>
    </BookmarkProvider>
  );
}
